services:
  webapp:
    build: 
      dockerfile: webapp.Dockerfile
      context: .
    environment:
      TZ: Europe/Prague
    ports:
      - "5000:5000"
    volumes:
      - ./userdata:/usr/src/app/userdata
  crawler:
    build:
      dockerfile: crawler.Dockerfile
      context: .
    environment:
      TZ: Europe/Prague
    volumes:
      - ./userdata:/usr/src/app/userdata